package caramel.forge;

import cpw.mods.fml.common.ModMetadata;

public class CaramelInfo {

	public static final String ID = "caramelapi";	
	public static final String NAME = "Caramel API for Minecraft Forge";
	public static final String VERSION = "1.7.10-1.0.0.0";
	public static final String MC_VERSION = "1.7.10";
	public static final String API_VERSION = "0.1";
	public static final String DESCRIPTION = "Caramel API for Minecraft Forge Mods";
	public static final String AUTHOR = "jwoo__";
	public static final String CREDITS = "jwoo Kim";
	public static final String URL = "http://jwoop.tistory.com";
	public static final String UPDATE_URL = "";
	
	public static final void setupMetadata(ModMetadata data) {
		data.autogenerated = false;
		data.modId = ID;
		data.name = NAME;
		data.version = VERSION;
		data.description = DESCRIPTION;
		data.authorList.add(AUTHOR);
		data.credits = CREDITS;
		data.url = URL;
		data.updateUrl = UPDATE_URL;
	}
	
}
