package mint.seobaragi;

import static library.ColorCode.Cd;
import library.Reference;
import mint.seobaragi.command.CommandReset;
import mint.seobaragi.entity.EntityDust;
import mint.seobaragi.event.PlayerEventHandler;
import mint.seobaragi.event.ServerMiscellaneousEventHandler;
import mint.seobaragi.proxy.CommonProxy;
import net.minecraft.init.Blocks;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerAboutToStartEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.registry.EntityRegistry;

@Mod(modid = Reference.MODID, name = Reference.NAME ,version = Reference.VERSION, acceptedMinecraftVersions = "1.7.10", acceptableRemoteVersions = "1.7.10")
public class TtaemiriKingMod
{
	@Instance(value = Reference.MODID)
	public static TtaemiriKingMod instance;
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.SERVER_PROXY_CLASS)
	public static CommonProxy proxy;
	
	//mcmod.info
	public void setupModMetadata(ModMetadata data)
	{
		data.autogenerated = false;
		data.modId = Reference.MODID;
		data.name = Reference.NAME;
		data.description = "양띵TV 서넹 릴레이 컨텐츠 때밀이왕을 위해 제작된 모드입니다.";
		data.version = Reference.VERSION;
		data.authorList.add("MintSol_");
		data.authorList.add("jwoo__");
		data.credits = "제작자 : 민솔, 정우";
		data.logoFile = "Logo.png";
	}
	
    @EventHandler
    public void preinit(FMLPreInitializationEvent event)
    {
    	setupModMetadata(event.getModMetadata());
    	
    	SeonengItems.init();
    	SeonengItems.register();
    	
    	proxy.registerRenderers();
    	EntityRegistry.registerModEntity(EntityDust.class, "Dust", 0, this, 80, 3, true);
    	
    	proxy.registerGuiEventHandler();

    	MinecraftForge.EVENT_BUS.register(new PlayerEventHandler());
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event) {}
    
    @EventHandler
    public void postinit(FMLPostInitializationEvent event) {}
    
    @EventHandler
    public void serverPreInit(FMLServerAboutToStartEvent e) {
    	proxy.registerServerSideHandlers();
    }
    
    @EventHandler
    public void serverInit(FMLServerStartingEvent e) {
    	e.registerServerCommand(new CommandReset());
    }
    
}
