package noah.minecraft.runaway;

import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.StatCollector;
import net.minecraftforge.fml.common.ModMetadata;

public class Common {
	
	public static final String MOD_ID = "noahrunaway";
	public static final String MOD_VERSION = "1.0.2-dev";
	public static final String MOD_NAME = "½ºÆÝÁö¸¦ °®°í Æ¢¾î¶ó!";
	public static final String MOD_AUTHOR = "jwoo__";
	public static final String MOD_CREDIT = "Noah";
	public static final String MOD_DESCRIPTION = EnumChatFormatting.DARK_RED + "»ï½Ä´ÔÀÌ ÀÇ·ÚÇÏ½Å "+ 
	                                             EnumChatFormatting.YELLOW + "½ºÆÝÁö" +
			                                     EnumChatFormatting.WHITE + "¸¦ °®°í " +
			                                     EnumChatFormatting.RED + "Æ¢¾î¶ó!" +
			                                     EnumChatFormatting.WHITE + " ¸ðµå ÀÔ´Ï´Ù.";
	public static final String MOD_LOGO_DIR = "assets/" + MOD_ID + "/textures/misc/logo.png";
	
	public static void setupModMetadata(ModMetadata data) {
		data.autogenerated = false;
		data.name = EnumChatFormatting.BLUE + MOD_NAME;
		data.authorList.add(MOD_AUTHOR);
		data.credits = EnumChatFormatting.YELLOW + MOD_CREDIT;
		data.description = MOD_DESCRIPTION;
		data.logoFile = MOD_LOGO_DIR;
	}
}
